---
sudo: required
language: python
services:
  - docker

env:
  global:
    - ROLE_NAME: test-travis

before_install:
  - cd ../
  - mv ansible-role-$ROLE_NAME ominous48.$ROLE_NAME
  - cd ominous48.$ROLE_NAME

#install:
#  - pip install molecule docker

script:
#  - molecule test
  - tox
